name: build-base

on:
  # Manual test builds (no push needed)
  workflow_dispatch:
    inputs:
      tag:
        description: "Test tag (e.g., dev, test-2025-10-01)"
        required: true
        default: "dev"

  # Release builds (only when you publish a v* tag)
  push:
    tags: [ "v*" ]

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # -------- Release path: tag like v0.1.0 --------
      - name: Docker meta (release)
        id: meta_release
        if: startsWith(github.ref, 'refs/tags/v')
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # base-v0.1.0
            type=semver,pattern={{version}},prefix=base-
            # base-0.1
            type=semver,pattern={{major}}.{{minor}},prefix=base-
            # base-v0.1.0 (keep the v* tag too if you like)
            type=ref,event=tag,prefix=base-
          flavor: |
            latest=true

      # -------- Manual test path: input tag becomes base-<tag> --------
      - name: Docker meta (manual test)
        id: meta_test
        if: github.event_name == 'workflow_dispatch'
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=base-${{ inputs.tag }}
          flavor: |
            latest=false

      # Build & push (release)
      - name: Build & push (release)
        if: steps.meta_release.outputs.tags != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base/Dockerfile
          push: true
          tags: ${{ steps.meta_release.outputs.tags }}
          labels: ${{ steps.meta_release.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # Build & push (manual test)
      - name: Build & push (manual test)
        if: steps.meta_test.outputs.tags != ''
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base/Dockerfile
          push: true
          tags: ${{ steps.meta_test.outputs.tags }}
          labels: ${{ steps.meta_test.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
