name: build base (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Dev tag (e.g., dev, test-2025-10-03)"
        required: true
        default: "dev"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (manual)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=base-${{ inputs.tag }}
          flavor: |
            latest=false

      - name: Build & push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
