name: build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]              # build/push when you publish vX.Y.Z
  workflow_dispatch:

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/freeradical16/sd-webui-hub
          tags: |
            # when pushing to main
            type=raw,value=main,enable=${{ github.ref == 'refs/heads/main' }}
            # always add a short-sha tag
            type=sha,format=short,prefix=sha-
            # if this is a tag like v0.1.0, add that exact tag
            type=ref,event=tag
            # and also mark it as latest when it's a v* tag
            type=raw,value=latest,enable=${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
