name: build

on:
  push:
    branches: [ "main" ]
    tags: [ "v*" ]   # build/push when you publish v0.1.0 etc.
  workflow_dispatch:

# IMPORTANT: allow Actions to publish to GHCR
permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
      - uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Generate tags/labels automatically:
      # - On main:   ghcr.io/<user>/sd-webui-hub:main and :sha-<shortsha>
      # - On tag vX: ghcr.io/<user>/sd-webui-hub:vX and :latest
      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/freeradical16/sd-webui-hub
          tags: |
            type=raw,value=main,enable={{is_default_branch}}
            type=sha,format=short,prefix=sha-
            type=ref,event=tag
            type=raw,value=latest,enable={{is_tag}}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          # optional cache (speeds up subsequent builds)
          cache-from: type=gha
          cache-to: type=gha,mode=max
