name: build a1111 (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Test tag (e.g., dev, test-2025-10-02)"
        required: true
        default: "dev"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (manual test)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=raw,value=a1111-${{ inputs.tag }}
          flavor: |
            latest=false

      - name: Build & push (manual test)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./a1111/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
