name: build a1111 (manual)

on:
  workflow_dispatch:
    inputs:
      tag:
        description: "Dev tag (e.g., dev, test-2025-10-04)"
        required: true
        default: "dev"

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & push (manual dev)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./a1111/Dockerfile
          push: true
          tags: ghcr.io/${{ github.repository }}:a1111-${{ inputs.tag }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
