name: release-base

on:
  push:
    tags:
      - "base-v*.*.*"   # e.g., base-v0.2.0

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (release)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # base-v0.2.0
            type=semver,pattern={{version}},prefix=base-
            # base-0.2
            type=semver,pattern={{major}}.{{minor}},prefix=base-
          flavor: |
            latest=true
          labels: |
            org.opencontainers.image.title=sd-webui-hub (base)
            org.opencontainers.image.description=Base CUDA + Jupyter image for sd-webui-hub
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build & push (release)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
