name: release base

on:
  push:
    tags:
      - "v*.*.*"   # e.g., v0.1.0

permissions:
  contents: read
  packages: write

jobs:
  base:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (semver + base-latest)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            type=semver,pattern={{version}},prefix=base-
            type=semver,pattern={{major}}.{{minor}},prefix=base-
          flavor: |
            latest=false

      - name: Build & push (versioned tags)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./base/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      # push a component-scoped "latest" tag for clarity
      - name: Tag base-latest
        run: |
          REF="ghcr.io/${{ github.repository }}"
          DIGEST="$(docker buildx imagetools inspect "${REF}:$(echo "${{ steps.meta.outputs.tags }}" | head -n1 | sed 's/.*://')" --format '{{json .Manifest.Digest}}' | tr -d '"')"
          docker buildx imagetools create -t "${REF}:base-latest" "${REF}@${DIGEST}"
