name: release-a1111

on:
  push:
    tags:
      - "a1111-v*.*.*"   # e.g., a1111-v1.10.1

permissions:
  contents: read
  packages: write

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Docker meta (release)
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}
          tags: |
            # a1111-v1.10.1
            type=semver,pattern={{version}},prefix=a1111-
            # a1111-1.10
            type=semver,pattern={{major}}.{{minor}},prefix=a1111-
          flavor: |
            latest=true
          labels: |
            org.opencontainers.image.title=sd-webui-hub (a1111)
            org.opencontainers.image.description=Automatic1111 image on sd-webui-hub base
            org.opencontainers.image.source=https://github.com/${{ github.repository }}

      - name: Build & push (release)
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./a1111/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          provenance: mode=max
